spring.application.name=null-space

# 시스템 환경 변수에서 키를 가져옴
youtube.api.key=${YOUTUBE_API_KEY}

# h2 DB를 메모리가 아닌 파일로 저장
spring.datasource.url=${DB_URL}
# 서버가 꺼져도 파일에 저장됨
spring.datasource.driverClassName=org.h2.Driver

# H2 콘솔 보안 및 접속 설정
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 아래 설정을 추가하여 접속 권한 문제를 완화합니다
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA 설정 (필수)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true